xcodeproj 'RKData'
workspace '../RKData'

platform :ios, '7.0'

target :RKDataExample do
  pod 'RKData', :path => '../'
end

target :RKDataTests do
  pod 'Expecta', '~> 0.2.3'
  pod 'Specta',  '~> 0.2.1'
  pod 'OCMock',  '~> 2.2'
  pod 'RKData', :path => '../'
end
